services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
    volumes:
      - ./backend/api/data:/app/backend/api/data:ro
      - ./backend/api/data/.easyocr:/root/.EasyOCR

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3200:3000"
    environment:
      WATCHPACK_POLLING: "true"
